tritonJS826/masters-way

mw-webapp/src/firebase.ts
mw-webapp/src/utils/useAuth.ts

Now we use only Ekaterina's Firebase project for auth and db.

#19 feat: got rid of the second firebase configuration

---

mw-webapp/src/component/table/Table.tsx
mw-webapp/src/dataAccessLogic/getDayReports.ts
mw-webapp/src/pages/allUsersPage/AllUsersPage.tsx
mw-webapp/src/pages/usersPage/UsersPage.tsx
mw-webapp/src/router/Router.tsx
mw-webapp/src/router/pages.tsx

feat: #98 create AllUsersPage

---

mw-webapp/src/component/table/columns.tsx

fix: #87 fix merge conflict issue

---

mw-webapp/.eslintrc

Add a rule to eslint to ignore storybook

feat: #87 update eslint

---

mw-webapp/src/component/header/Header.tsx

If a user is logged in, his/her name is displayed in the header

feat: #149 Show the user name after a successful login

---

mw-webapp/src/logic/aboutProjectPage/AboutProjectPage.module.scss
mw-webapp/src/logic/aboutProjectPage/AboutProjectPage.tsx
mw-webapp/src/styles/_variables.scss

Added an accordion component to the  about project page

feat: #150 add an accordion component to the  about project page (150)

---

mw-webapp/src/component/accordion/Accordion.cy.tsx
mw-webapp/src/component/accordion/Accordion.stories.tsx
mw-webapp/src/component/accordion/Accordion.tsx
mw-webapp/src/component/accordion/AccordionContent/AccordionContent.tsx
mw-webapp/src/component/accordion/AccordionItem/AccordionItem.tsx
mw-webapp/src/component/accordion/AccordionTrigger/AccordionTrigger.tsx
mw-webapp/src/helpers/getDataCy.ts
mw-webapp/src/logic/aboutProjectPage/AboutProjectPage.tsx
mw-webapp/src/utils/cyTesting/getDataCy.ts

Implemented tests for Accordion component.

feat: #188 Add 6 tests for Accordion

---

mw-webapp/package.json
mw-webapp/pnpm-lock.yaml
mw-webapp/src/dataAccessLogic/BusinessToDTOConverter/currentProblemToCurrentProblemDTOConverter.ts
mw-webapp/src/dataAccessLogic/BusinessToDTOConverter/dayReportToDayReportDTOConverter.ts
mw-webapp/src/dataAccessLogic/BusinessToDTOConverter/jobDoneToJobDoneDTOConverter.ts
mw-webapp/src/dataAccessLogic/BusinessToDTOConverter/mentorCommentToMentorCommentDTOConverter.ts
mw-webapp/src/dataAccessLogic/BusinessToDTOConverter/planForNextPeriodToPlanForNextPeriodDTOConverter.ts
mw-webapp/src/model/DTOModel/CurrentProblemDTO.ts
mw-webapp/src/model/DTOModel/DayReportDTO.ts
mw-webapp/src/model/DTOModel/GoalDTO.ts
mw-webapp/src/model/DTOModel/GoalMetricDTO.ts
mw-webapp/src/model/DTOModel/JobDoneDTO.ts
mw-webapp/src/model/DTOModel/MentorCommentDTO.ts
mw-webapp/src/model/DTOModel/MonthReportDTO.ts
mw-webapp/src/model/DTOModel/PlanForNextPeriodDTO.ts
mw-webapp/src/model/DTOModel/UserDTO.ts
mw-webapp/src/model/DTOModel/WayDTO.ts
mw-webapp/src/service/CurrentProblemService.ts
mw-webapp/src/service/DayReportService.ts
mw-webapp/src/service/GoalService.ts
mw-webapp/src/service/JobDoneService.ts
mw-webapp/src/service/MentorCommentService.ts
mw-webapp/src/service/PlanForNextPeriodService.ts
mw-webapp/src/service/UserService.ts
mw-webapp/src/service/WayService.ts
mw-webapp/src/service/auth/writeNewUserCredentials.ts

Converted only DayReportDTO, if its ok will convert everything else too.

feat: #217 Add runtime validation to service layer (all methods)

---

mw-webapp/src/firebase.ts
mw-webapp/src/service/auth/logIn.ts

1. Change signInWithRedirect method to signInWithPopup
2. Added prompt option to GoogleAuthProvider in firebase.ts file to ask the user which Google account he wants to use.

refactor: #168 fix login chromium

---

mw-webapp/src/logic/wayPage/reportsTable/WayColumns.tsx
mw-webapp/src/service/DayReportService.ts
mw-webapp/src/service/converter/querySnapshotsToDTOConverter.ts
mw-webapp/src/utils/getChunkArray.ts

Added multiple queries
Updated WayColumns for add ability mentors to edit cells in DayReportsTable

feat: #276 Make multiple queries

---

mw-webapp/src/component/accordion/Accordion.module.scss
mw-webapp/src/component/button/Button.module.scss
mw-webapp/src/component/button/Button.stories.tsx
mw-webapp/src/component/inProgress/InProgress.module.scss
mw-webapp/src/component/modal/ModalContent/ModalContent.module.scss
mw-webapp/src/component/sidebar/Sidebar.module.scss
mw-webapp/src/component/sidebar/SidebarContent/SidebarContent.module.scss
mw-webapp/src/component/table/Table.module.scss
mw-webapp/src/component/tooltip/Tooltip.module.scss
mw-webapp/src/logic/page404/Page404.module.scss
mw-webapp/src/logic/wayPage/reportsTable/WayColumns.module.scss
mw-webapp/src/styles/_variables.scss

Struggle with adding styles for different button sizes.
Maybe we need to add style for the focus state because it has different styles in variable browsers.

feat: #284 Add styles for button component

---

.gitignore
docs/DTOmodels.md
docs/coreFeatures.md
mw-migrations/backups/README.md
mw-migrations/migration-logs/2024-01-11T02-34-52.354Z_firebase.log.txt
mw-migrations/package.json
mw-migrations/src/backup/dayReports.ts
mw-migrations/src/backup/exportAllCollections.ts
mw-migrations/src/backup/goals.ts
mw-migrations/src/backup/users.ts
mw-migrations/src/backup/ways.ts
mw-migrations/src/service/DayReportService.ts
mw-migrations/src/service/GoalService.ts
mw-migrations/src/utils/writeBackup.ts

Ekaterina, could you help me to actualize DTO models, please? YOu can push update in the current PR

feat: #370 backup database

---

mw-webapp/src/component/checkbox/Сheckbox.module.scss
mw-webapp/src/component/checkbox/Сheckbox.tsx
mw-webapp/src/logic/wayPage/WayPage.module.scss
mw-webapp/src/logic/wayPage/reportsTable/WayColumns.module.scss
mw-webapp/src/styles/_variables.scss

Theme variables aren't available in storybook

feat: #285 add styles for checkbox component

---

mw-webapp/src/component/progressBar/ProgressBar.module.scss
mw-webapp/src/component/progressBar/ProgressBar.stories.tsx

1. Create story
2. center text in the progress bar

feat: #424 Add progress bar to storybook

---

mw-webapp/src/logic/wayPage/wayStatistics/WayStatistic.tsx
mw-webapp/src/utils/DateUtils.ts

1.  Change the day count
2.  Refactor

feat: #434 Change the time count  for a week and two weeks

---

mw-webapp/src/logic/wayPage/MentorRequestsSection.module.scss
mw-webapp/src/logic/wayPage/MentorRequestsSection.tsx

Fix accept-decline styles in MentorRequestsSection

Fix: #384 Fix accept-decline styles in MentorRequestsSection

---

mw-webapp/src/logic/wayPage/wayStatistics/WayStatistic.tsx

fix: #415 fix statistics

---

mw-webapp/src/logic/wayPage/wayStatistics/StatisticLine.tsx
mw-webapp/src/logic/wayPage/wayStatistics/TagStats.tsx

1. Add tags to statistics instead of plain text

feat: #422 add tags to statistics

---

mw-webapp/src/component/tooltip/Tooltip.module.scss

feat: #506 add delay 1s to tooltip

---

mw-webapp/src/component/editableText/renderSpan.module.scss
mw-webapp/src/component/editableText/renderSpan.tsx
mw-webapp/src/component/input/Input.module.scss
mw-webapp/src/component/textarea/Textarea.module.scss
mw-webapp/src/component/textarea/Textarea.tsx
mw-webapp/src/logic/wayPage/goalBlock/GoalBlock.module.scss

Mw 411/adjust textarea

---

mw-webapp/src/App.tsx
mw-webapp/src/GlobalContext.ts
mw-webapp/src/component/layout/Layout.tsx
mw-webapp/src/hooks/useLoad.ts
mw-webapp/src/index.tsx
mw-webapp/src/logic/initializedApp/InitializedApp.tsx
mw-webapp/src/logic/page404/Page404.module.scss
mw-webapp/src/logic/page404/Page404.tsx
mw-webapp/src/logic/userPage/UserPage.tsx
mw-webapp/src/logic/wayPage/WayPage.tsx
mw-webapp/src/router/Router.tsx

feat: #394 add errorElement to Route

---

mw-webapp/src/logic/allUsersPage/AllUsersPage.tsx
mw-webapp/src/router/Router.tsx

add header when error occured to AllusersPage and AllWaysPage

fix: #553 add header when error occured

---

mw-webapp/src/component/editableText/renderSpan.tsx
mw-webapp/src/hooks/usePersistanceState.tsx
mw-webapp/src/logic/userPage/UserPage.tsx
mw-webapp/src/router/Router.tsx

get rid of errors in thr console

fix: #548 get rid of errors in thr console

---

mw-webapp/src/component/table/Table.module.scss
mw-webapp/src/component/verticalContainer/VerticalContainer.module.scss
mw-webapp/src/logic/page404/Page404.module.scss
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/ReportsColumns.module.scss
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/ReportsColumns.tsx

1. Rid of absolute positioning at columns

fix: #399 get rid of absolute positioning

---

mw-webapp/src/component/checkbox/Сheckbox.cy.tsx
mw-webapp/src/component/checkbox/Сheckbox.tsx
mw-webapp/src/component/header/Header.cy.tsx
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/component/input/Input.cy.tsx
mw-webapp/src/component/input/Input.tsx

- add tests to header
-  add tests to checkbox
-  add tests to input

Mw 188/add test checkbox header

---

mw-webapp/src/component/header/Header.tsx
mw-webapp/src/dictionary/AboutProjectPageContent.json
mw-webapp/src/dictionary/AllUsersPageContent.json
mw-webapp/src/dictionary/AllWaysPageContent.json
mw-webapp/src/dictionary/Header.json
mw-webapp/src/dictionary/SettingsPageContent.json
mw-webapp/src/dictionary/Sidebar.json
mw-webapp/src/dictionary/UserPageContent.json
mw-webapp/src/dictionary/WayPageContent.json
mw-webapp/src/utils/LanguageWorker.ts

feat: #415 add ukrainian localization

---

mw-webapp/src/component/confirm/Confirm.cy.tsx
mw-webapp/src/component/confirm/Confirm.tsx
mw-webapp/src/component/modal/Modal.tsx

test: #188 confirm

---

mw-webapp/src/component/userCard/UserCard.cy.tsx
mw-webapp/src/component/userCard/UserCard.tsx
mw-webapp/src/component/verticalContainer/VerticalContainer.cy.tsx
mw-webapp/src/component/verticalContainer/VerticalContainer.tsx
mw-webapp/src/component/wayCard/WayCard.cy.tsx
mw-webapp/src/component/wayCard/WayCard.tsx

- created tests to userCard
- created tests to wayCard
- created tests to Vertical container

feat: #188 add tests wayCard, userCars, VerticalContainer

---

mw-webapp/src/component/dropdown/Dropdown.cy.tsx
mw-webapp/src/component/dropdown/Dropdown.tsx
mw-webapp/src/component/dropdown/dropdownMenuItem/DropdownMenuItem.tsx

feat: #188 add test to dropdown

---

mw-webapp/src/component/image/Image.cy.tsx
mw-webapp/src/component/image/Image.tsx
mw-webapp/src/component/loader/Loader.cy.tsx
mw-webapp/src/component/loader/Loader.tsx

- create tests to Icon Component
- create tests to Loader Component

Mw 188/create tests image loader

---

mw-webapp/src/component/horizontalContainer/HorizontalContainer.cy.tsx
mw-webapp/src/component/horizontalContainer/HorizontalContainer.tsx
mw-webapp/src/component/horizontalGridContainer/HorizontalGridContainer.cy.tsx
mw-webapp/src/component/horizontalGridContainer/HorizontalGridContainer.tsx
mw-webapp/src/component/progressBar/ProgressBar.cy.tsx
mw-webapp/src/component/progressBar/ProgressBar.tsx
mw-webapp/src/component/scrollableBlock/ScrollableBlock.cy.tsx
mw-webapp/src/component/scrollableBlock/ScrollableBlock.tsx

- add tests to Progressbar
- add tests to HorizontalContainer
- add tests to HorizontalGridContainer
- add tests to ScrollableBlock

Mw 188/create progressbar tests

---

mw-webapp/src/component/editableText/EditableText.cy.tsx
mw-webapp/src/component/editableText/EditableText.tsx

feat: #188 add test to editable text

---

mw-webapp/src/component/editableTextarea/EditableTextarea.cy.tsx
mw-webapp/src/component/editableTextarea/editableTextarea.tsx
mw-webapp/src/component/textarea/Textarea.cy.tsx
mw-webapp/src/component/textarea/Textarea.tsx

1. Add tests to textarea
2. Add tests to editable textarea

test: #188 add tests to textarea and editable-textarea

---

mw-webapp/src/assets/icons/EyeOpenedIcon.tsx
mw-webapp/src/assets/icons/EyeSlashedIcon.tsx
mw-webapp/src/assets/icons/FileIcon.tsx
mw-webapp/src/assets/icons/GridViewIcon.tsx
mw-webapp/src/assets/icons/MoonIcon.tsx
mw-webapp/src/assets/icons/MoreVertical.tsx
mw-webapp/src/assets/icons/PlusIcon.tsx
mw-webapp/src/assets/icons/StarIcon.tsx
mw-webapp/src/assets/icons/SunIcon.tsx
mw-webapp/src/assets/icons/TableViewIcon.tsx
mw-webapp/src/component/icon/Icon.cy.tsx
mw-webapp/src/component/icon/Icon.module.scss
mw-webapp/src/component/icon/Icon.tsx

feat: #188 add test icon

---

mw-webapp/src/component/tag/Tag.module.scss

resolved this problem https://github.com/tritonJS826/masters-way/issues/761
https://github.com/tritonJS826/masters-way/assets/112805668/10c05184-3b4b-42cb-aa67-b115c732171e

fix: #761 fixed mistake with incorrect display a cross button in Tag

---

mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.module.scss
mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.tsx
mw-webapp/src/logic/wayPage/labels/AdjustLabelsModalContent.module.scss
mw-webapp/src/logic/wayPage/labels/AdjustLabelsModalContent.tsx

resolved problem in this task https://github.com/tritonJS826/masters-way/issues/723
https://github.com/tritonJS826/masters-way/assets/112805668/a4f92256-3639-44c6-ad15-26c04ce68c1c

fix: #723 fixed mistake with Add tag button

---

mw-webapp/src/component/accordion/AccordionTrigger/AccordionTrigger.module.scss
mw-webapp/src/component/tooltip/Tooltip.module.scss

resolved this bag https://github.com/tritonJS826/masters-way/issues/697
https://github.com/tritonJS826/masters-way/assets/112805668/429af652-e38c-4c08-9058-5a2035a36fae

feat: #743 changed border-color to tooltip

---

mw-server/controllers/comment.controller.go
mw-server/controllers/compositeWay.controller.go
mw-server/controllers/dayReport.controller.go
mw-server/controllers/favoriteUser.controller.go
mw-server/controllers/favoriteUserWay.controller.go
mw-server/controllers/fromUserMentoringRequest.controller.go
mw-server/controllers/jobDone.controller.go
mw-server/controllers/jobDoneJobTag.controller.go
mw-server/controllers/jobTag.controller.go
mw-server/controllers/mentorUserWay.controller.go
mw-server/controllers/metric.controller.go
mw-server/controllers/plan.controller.go
mw-server/controllers/planJobTag.controller.go
mw-server/controllers/problem.controller.go
mw-server/controllers/problemJobTag.controller.go
mw-server/controllers/toUserMentoringRequest.controller.go
mw-server/controllers/user.controller.go
mw-server/controllers/userTag.controller.go
mw-server/controllers/way.controller.go
mw-server/controllers/wayCollection.controller.go
mw-server/controllers/wayCollectionWay.controller.go
mw-server/controllers/wayTag.controller.go
mw-server/util/handleErrorGin.go

feat: #792 update way when day report created

---

mw-webapp/src/logic/userPage/UserPage.tsx

fix: #852 fixed no-tags in profile user

---

mw-webapp/src/component/tooltip/Tooltip.module.scss

https://github.com/tritonJS826/masters-way/assets/112805668/b19cc5c4-6ba9-46ee-af73-a7bcabfab544

fix: #697 fixed styles in Tooltip

---

.github/ISSUE_TEMPLATE/suggestion.md

Add GitHub template for suggestion

---

mw-webapp/src/logic/wayPage/wayStatistics/WayStatistic.tsx

- fixed the correct display of statistics graphs
- fixed the correct display of statistics data

fix: #810 fixed month and week statistics

---

.gitignore
mw-server/controllers/user.controller.go
mw-server/schemas/users.schema.go
mw-webapp/src/component/select/Select.cy.tsx

https://github.com/tritonJS826/masters-way/issues/673

fix: #673 Application not save empty 'About' field on user page

---

mw-webapp/cypress/accessIds/aboutProjectAccessIds.ts
mw-webapp/cypress/accessIds/allUsersAccessIds.ts
mw-webapp/cypress/accessIds/navigationMenuIds.ts
mw-webapp/cypress/e2e/allWays.cy.ts
mw-webapp/cypress/e2e/home.cy.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/fixtures/aboutProjectPageFixure.json
mw-webapp/cypress/fixtures/allUsersFixture.json
mw-webapp/cypress/scopesSelectors/aboutProjectSelectors.ts
mw-webapp/cypress/scopesSelectors/allUsersSelectors.ts
mw-webapp/cypress/scopesSelectors/allWaysSelectors.ts
mw-webapp/cypress/scopesSelectors/navigatioMenuSelectors.ts
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/logic/aboutProjectPage/AboutProjectPage.tsx
mw-webapp/src/logic/allUsersPage/AllUsersPage.tsx

Add Navigation menu link tests:
NoAuth_NavMenu_AllUsers
NoAuth_NavMenu_AllWays
NoAuth_NavMenu_About 
NoAuth_NavMenu_Home
NoAuth_NavMenu_Light_MastersWayLogo
related to https://github.com/tritonJS826/masters-way/issues/1001

feat: #1001 add NoAuthNavMenu link tests

---

mw-webapp/src/styles/_variables.scss

This PR contains the fix for all asymmetrical buttons.
Closes #760

Fix: #760 asymmetrical Plus buttons

---

mw-webapp/src/component/chart/AreaChart.tsx
mw-webapp/src/logic/wayPage/wayStatistics/WayActiveStatistic.tsx
mw-webapp/src/logic/wayPage/wayStatistics/WayStatistic.tsx
mw-webapp/src/utils/DateUtils.ts

fixed Statistics: the chart does not show tasks completed on the first day

fix: #795  the chart does not show tasks completed on the first day

---

mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTablePlansCell/copyPlanToJobDoneModalContent/CopyPlanToJobDoneModalContent.tsx

add time and description to plan

fix: #965 add description and time to

---

mw-webapp/src/logic/wayPage/goalMetricsBlock/GoalMetricItem.module.scss
mw-webapp/src/logic/wayPage/goalMetricsBlock/GoalMetricItem.tsx

fix: #955 fixed editable goalMetrics

---

gateway/localQA.nginx.conf
localQA.docker-compose.yml

https://github.com/tritonJS826/masters-way/issues/1034

fix: #1034 Fix nginx SSL issue in local QA version by creating localQA.nginx.conf

---

mw-webapp/src/component/checkbox/Checkbox.module.scss
mw-webapp/src/component/input/Input.module.scss
mw-webapp/src/component/progressBar/ProgressBar.module.scss
mw-webapp/src/component/tooltip/Tooltip.module.scss
mw-webapp/src/logic/allUsersPage/AllUsersPage.tsx
mw-webapp/src/logic/wayPage/goalMetricsBlock/GoalMetricItem.module.scss
mw-webapp/src/styles/_variables.scss

align design for 
- checkbox, 
- ProgressBar, 
- Input, 
- Tooltip

feat: #1057 align design for checkbox, progressBar, Input, Tooltip

---

mw-webapp/cypress/accessIds/headerAccessIds.ts
mw-webapp/cypress/accessIds/navigationMenuIds.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/scopesSelectors/headerSelectors.ts
mw-webapp/cypress/scopesSelectors/navigationMenuSelectors.ts
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/component/select/Select.tsx
mw-webapp/src/logic/Layout.tsx

Tests added:
NoAuth_NavMenu_Close
NoAuth_NavMenu_Home_Language
Comment:
Not sure about 177 line in mw-webapp/src/component/select/Select.tsx

feat: #1001 add NoAuth_NavMenu_Close and NoAuth_NavMenu_Home_Language tests

---

mw-webapp/cypress/accessIds/navigationMenuIds.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/fixtures/navigationMenuFixture.json
mw-webapp/cypress/scopesSelectors/navigationMenuSelectors.ts
mw-webapp/cypress/support/commands.ts
mw-webapp/cypress/support/index.d.ts
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/component/themeSwitcher/ThemeSwitcher.tsx
mw-webapp/src/globalStore/ThemeStore.ts

Link tests refactored: added a check that the navigation menu closes after clicking on a link.
The assert is commented for NoAuth_NavMenu_MastersWayLogo test, the menu does not close, bug is being fixed.
Added tests: 
NoAuth_NavMenu_CloseButton
NoAuth_NavMenu_DarkMode
NoAuth_NavMenu_LightMode
NoAuth_NavMenu_LinkedinLink
NoAuth_NavMenu_YoutubeLink

feat: #1001 add DarkMode LightMode LinkedinLink YoutubeLink CloseButton tests

---

mw-webapp/cypress/accessIds/allWaysAccessIds.ts
mw-webapp/cypress/accessIds/headerAccessIds.ts
mw-webapp/cypress/accessIds/navigationMenuIds.ts
mw-webapp/cypress/accessIds/settingsAccessIds.ts
mw-webapp/cypress/e2e/allWays.cy.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/fixtures/settingsFixture.json
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/scopesSelectors/allWaysSelectors.ts
mw-webapp/cypress/scopesSelectors/headerSelectors.ts
mw-webapp/cypress/scopesSelectors/navigationMenuSelectors.ts
mw-webapp/cypress/scopesSelectors/settingsSelectors.ts
mw-webapp/cypress/support/commands.ts
mw-webapp/cypress/support/index.d.ts
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/logic/settingsPage/SettingsPage.tsx

Added:
IsAuth_NavMenu_PersonalArea
IsAuth_NavMenu_Settings
IsAuth_NavMenu_LogoutButton
Removed:
NoAuth_AllWays_Open

feat: #1092 Add IsAuth Navigation menu scope tests

---

mw-webapp/src/component/button/Button.module.scss

Aligned styles with the design for Button component.

feat: #1057 align design for Button component

---

mw-webapp/src/component/link/Link.module.scss
mw-webapp/src/component/sidebar/Sidebar.module.scss
mw-webapp/src/component/userCard/UserCard.module.scss
mw-webapp/src/component/wayCard/WayCard.module.scss
mw-webapp/src/logic/wayPage/WayPage.module.scss

Aligned styles with the design for Link component.

feat: #1057 align design for Link component

---

mw-webapp/src/assets/icons/ChevronIcon.tsx
mw-webapp/src/component/checkbox/Checkbox.module.scss
mw-webapp/src/component/icon/Icon.tsx
mw-webapp/src/component/input/Input.module.scss
mw-webapp/src/component/progressBar/ProgressBar.module.scss
mw-webapp/src/component/select/Select.module.scss
mw-webapp/src/component/select/Select.tsx
mw-webapp/src/component/select/selectItem/SelectItem.tsx
mw-webapp/src/component/toggle/Toggle.module.scss
mw-webapp/src/globalStore/ThemeStore.ts
mw-webapp/src/logic/allUsersPage/AllUsersPage.tsx
mw-webapp/src/logic/allWaysPage/AllWaysPage.tsx
mw-webapp/src/styles/_variables.scss

- started align design to select and toggle

Mw 1057/align design toggle select

---

mw-webapp/src/component/dropdown/Dropdown.module.scss
mw-webapp/src/component/dropdown/dropdownMenuItem/DropdownMenuItem.module.scss
mw-webapp/src/globalStore/ThemeStore.ts

fix: #1057 add align to dropdown

---

mw-webapp/cypress/accessIds/headerAccessIds.ts
mw-webapp/cypress/accessIds/navigationMenuAccessIds.ts
mw-webapp/cypress/accessIds/userPersonalDataAccessIds.ts
mw-webapp/cypress/e2e/header.cy.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/scopesSelectors/headerSelectors.ts
mw-webapp/cypress/scopesSelectors/navigationMenuSelectors.ts
mw-webapp/cypress/scopesSelectors/userPersonalDataSelectors.ts
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/logic/userPage/UserPage.tsx

Added tests:
NoAuth_Header_MasterWayIcon
NoAuth_Header_LightThemeSwitchIcon
NoAuth_Header_DarkThemeSwitchIcon
NoAuth_Header_LanguageSelect
NoAuth_Header_NavigationBurgerMenu (not sure if this test is needed)
IsAuth_Header_UserNameLink
IsAuth_Header_UserNameLinkOneWord
IsAuth_Header_NavigationBurgerMenu (not sure if this test is needed)

feat: #1151 Header scope tests

---

mw-server/controllers/auth.controller.go
mw-server/controllers/user.controller.go
mw-server/controllers/user.controller_test.go
mw-server/db/migration/000001_init_schema.up.sql
mw-server/db/query/users.query.sql
mw-server/db/sqlc/db.go
mw-server/db/sqlc/former_mentors_ways.query.sql.go
mw-server/db/sqlc/from_user_mentoring_requests.query.sql.go
mw-server/db/sqlc/mentors_ways.query.sql.go
mw-server/db/sqlc/models.go
mw-server/db/sqlc/users.query.sql.go
mw-server/docs/docs.go
mw-server/docs/swagger.json
mw-server/docs/swagger.yaml
mw-server/routes/user.route.go
mw-server/schemas/users.schema.go

- Removed all references to firebaseId from the database migrations and codebase.
- Remove from models.
- Remove from swagger

refactor: #1158 Remove firebaseId from migration and codebase

---

mw-webapp/cypress/accessIds/allWaysAccessIds.ts
mw-webapp/cypress/e2e/allWays.cy.ts
mw-webapp/cypress/fixtures/allWaysFixture.json
mw-webapp/cypress/scopesSelectors/allWaysSelectors.ts
mw-webapp/src/component/table/Table.cy.tsx
mw-webapp/src/component/table/Table.tsx
mw-webapp/src/component/viewSwitcher/ViewSwitcher.tsx
mw-webapp/src/logic/waysTable/WaysTable.tsx

Added:
NoAuth_AllWays_SelectTableView test

feat: #1118 NoAuth_AllWays_SelectTableView test

---

mw-webapp/src/component/header/Header.module.scss
mw-webapp/src/dataAccessLogic/DTOToPreviewConverter/wayDTOToWayPreview.ts

https://github.com/tritonJS826/masters-way/assets/112805668/b41e56c6-9c92-4071-ae9b-fe33bd2b599d

fix: #1057 fixed gap in header

---

mw-webapp/src/logic/homePage/HomePage.module.scss
mw-webapp/src/logic/homePage/HomePage.tsx

https://github.com/tritonJS826/masters-way/assets/112805668/9ea39f8b-3e26-45fc-b0f2-d2a8778ad36f

feat: #1012 add deskrop image to homePage

---

mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTablePlansCell/ReportsTablePlansCell.module.scss

https://github.com/tritonJS826/masters-way/assets/112805668/fb24e950-311a-402e-a3ff-cf8cf8031c5f

fix: #1171 fixed cursor checkbox

---

mw-webapp/src/component/avatar/Avatar.module.scss

feat: #1057 add styles to avatar component

---

mw-server/controllers/wayCollection.controller.go

https://github.com/tritonJS826/masters-way/issues/1237

fix: #1237 Changed LimitName for CreateWayCollection.

---

mw-webapp/src/component/userCard/UserCard.cy.tsx
mw-webapp/src/component/userCard/UserCard.module.scss
mw-webapp/src/component/userCard/UserCard.stories.tsx
mw-webapp/src/component/userCard/UserCard.tsx
mw-webapp/src/globalStore/ThemeStore.ts
mw-webapp/src/utils/DateUtils.ts

feat: #1104 Align design for User Card component

---

mw-webapp/src/dictionary/WayPageContent.json

fix: #878 fixed statistics title

---

mw-webapp/src/logic/wayPage/wayStatistics/statisticBlock/statisticItem/StatisticItem.tsx
mw-webapp/src/utils/convertMinutesToHours.ts

feat: #1252 update statistics in hours

---

mw-webapp/src/assets/icons/FlagIcon.tsx
mw-webapp/src/component/icon/Icon.tsx
mw-webapp/src/component/userCard/UserCard.module.scss
mw-webapp/src/component/userCard/UserCard.tsx
mw-webapp/src/globalStore/ThemeStore.ts

feat: #785 add menor flag

---

mw-webapp/src/component/editableText/EditableText.tsx
mw-webapp/src/component/label/Label.module.scss
mw-webapp/src/component/label/Label.tsx
mw-webapp/src/component/text/Text.tsx
mw-webapp/src/logic/wayPage/labels/LabelLine.tsx

https://github.com/tritonJS826/masters-way/assets/112805668/c71dde53-0d0a-4ba5-85f1-984fa2ec30cf

feat: #490 add logic editable to label

---

mw-webapp/src/component/modal/ModalContent/ModalContent.module.scss
mw-webapp/src/component/modal/PromptModalContent.module.scss
mw-webapp/src/component/modal/PromptModalContent.tsx
mw-webapp/src/dictionary/UserPageContent.json
mw-webapp/src/dictionary/WayPageContent.json
mw-webapp/src/globalStore/ThemeStore.ts
mw-webapp/src/logic/userPage/UserPage.tsx
mw-webapp/src/logic/wayPage/WayPage.tsx

feat: #1105 add align styles to tags, skills

---

mw-webapp/cypress/accessIds/allUsersAccessIds.ts
mw-webapp/cypress/accessIds/userPersonalDataAccessIds.ts
mw-webapp/cypress/e2e/allUsers.cy.ts
mw-webapp/cypress/e2e/allWays.cy.ts
mw-webapp/cypress/e2e/userPersonalData.cy.ts
mw-webapp/cypress/fixtures/userPersonalDataFixture.json
mw-webapp/cypress/scopesSelectors/allUsersSelectors.ts
mw-webapp/cypress/scopesSelectors/userPersonalDataSelectors.ts
mw-webapp/src/component/editableTextarea/editableTextarea.tsx
mw-webapp/src/component/title/Title.cy.tsx
mw-webapp/src/component/title/Title.tsx
mw-webapp/src/logic/aboutProjectPage/AboutProjectPage.tsx
mw-webapp/src/logic/allUsersPage/AllUsersPage.tsx
mw-webapp/src/logic/allWaysPage/AllWaysPage.tsx
mw-webapp/src/logic/homePage/HomePage.tsx
mw-webapp/src/logic/settingsPage/SettingsPage.tsx
mw-webapp/src/logic/userPage/UserPage.tsx
mw-webapp/src/logic/usersTable/UsersTable.tsx
mw-webapp/src/logic/wayPage/WayPage.tsx
mw-webapp/src/logic/waysTable/WaysTable.tsx

Added IsAuth_UserPersonalData_EditUserName test

feat: #1297 IsAuth User personal data scope tests

---

mw-webapp/src/component/button/Button.module.scss
mw-webapp/src/component/button/Button.tsx
mw-webapp/src/component/header/Header.module.scss
mw-webapp/src/component/header/Header.tsx
mw-webapp/src/logic/Layout.tsx
mw-webapp/src/router/Router.tsx

- refactor router
- add types to header
- add styles to login, loginButtom<burgerMenu
https://github.com/user-attachments/assets/58115d58-fc3f-49ba-9ad6-477ef29916a8

feat: #1279 add headerType

---

mw-webapp/src/component/button/Button.module.scss
mw-webapp/src/component/title/Title.module.scss
mw-webapp/src/dictionary/WayPageContent.json
mw-webapp/src/logic/wayPage/wayStatistics/statisticLabels/StatisticLabels.tsx
mw-webapp/src/logic/wayPage/wayStatistics/statisticLabels/statisticLine/StatisticLine.module.scss

https://github.com/user-attachments/assets/c9b28186-7428-4768-bf18-4bf2f54609af

feat: #1336 add align to statisticsBlock

---

mw-webapp/src/component/avatar/Avatar.module.scss
mw-webapp/src/component/avatar/Avatar.tsx

Fix Changed the background color of the Avatar component, now it does not merge with the background

fix: #1190 Avatar blends into the background

---

mw-webapp/cypress/accessIds/userWaysAccessIds.ts
mw-webapp/cypress/e2e/header.cy.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/e2e/userPersonalData.cy.ts
mw-webapp/cypress/e2e/userWays.cy.ts
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/fixtures/userWaysFixture.json
mw-webapp/cypress/scopesSelectors/userWaysSelectors.ts
mw-webapp/src/component/wayCollectionCard/WayCollectionCard.tsx
mw-webapp/src/logic/userPage/UserPage.tsx
mw-webapp/src/logic/waysTable/BaseWaysTable.tsx

Added tests:
NoAuth_UserWay_MentoringCollectionButton 
IsAuth_UserWays_CreateNewWay
Refactored:
NoAuth_UserWay_OwnWaysCollectionButton test
userWaysAccessIds, testUserDataFixture and userWaysSelectors

feat: #1339 add NoAuth_UserWay_MentoringCollectionButton test

---

mw-server/docs/docs.go
mw-server/docs/swagger.json
mw-server/docs/swagger.yaml
mw-server/main.go

Since I couldn't add the Swagger documentation for the health check inside the main function, I placed it at the top. I believe it's not worth creating a separate controller for this function. Also, we can't place it in the dev controller since the health check is used in prod."

fix: #1311 Added swagger docs for healthcheck.

---

mw-webapp/src/component/editableText/EditableText.tsx
mw-webapp/src/component/label/Label.tsx

feat: #1338 add notification maxLength to label

---

mw-webapp/src/component/avatar/Avatar.module.scss
mw-webapp/src/logic/wayPage/reportsTable/jobDoneTags/JobDoneTags.module.scss
mw-webapp/src/logic/wayPage/reportsTable/jobDoneTags/JobDoneTags.tsx
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableCommentsCell/ReportsTableCommentsCell.module.scss
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableCommentsCell/ReportsTableCommentsCell.tsx
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableJobsDoneCell/ReportsTableJobsDoneCell.module.scss
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableJobsDoneCell/ReportsTableJobsDoneCell.tsx
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTablePlansCell/ReportsTablePlansCell.module.scss
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTablePlansCell/ReportsTablePlansCell.tsx
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableProblemsCell/ReportsTableProblemsCell.module.scss
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableProblemsCell/ReportsTableProblemsCell.tsx

https://github.com/user-attachments/assets/52ad4608-9927-4e3f-b2e9-90b6d3947a62

feat: #1100 add response to dayReport

---

mw-webapp/src/component/sidebar/Sidebar.module.scss

https://github.com/user-attachments/assets/623f227c-a3d5-442c-8c45-b423e14b6906

feat: #1218 add scroll to sidebar

---

mw-webapp/cypress/accessIds/scenariosAccessIds/chatAccessIds.ts
mw-webapp/cypress/e2e/allUsers.cy.ts
mw-webapp/cypress/e2e/allWays.cy.ts
mw-webapp/cypress/e2e/header.cy.ts
mw-webapp/cypress/e2e/navigationMenu.cy.ts
mw-webapp/cypress/e2e/scenarios/chat.cy.ts
mw-webapp/cypress/e2e/userPersonalData.cy.ts
mw-webapp/cypress/e2e/userWays.cy.ts
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/scopesSelectors/scenariosSelectors/chatSelectors.ts
mw-webapp/cypress/support/commands.ts
mw-webapp/cypress/support/index.d.ts
mw-webapp/src/logic/chat/Chat.tsx

Added login(), logout(), resetDb() commands;
Changed test users data: names, emails;
Added check of message amount in "User should be able to receive a message from another user in the chat" test.

feat: #1432 test refactoring

---

mw-webapp/cypress/e2e/allUsers.cy.ts
mw-webapp/cypress/e2e/scenarios/chat.cy.ts
mw-webapp/cypress/e2e/scenarios/userProfile.cy.ts
mw-webapp/cypress/e2e/userPersonalData.cy.ts
mw-webapp/cypress/e2e/userWays.cy.ts
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/scopesSelectors/allUsersSelectors.ts
mw-webapp/cypress/support/commands.ts
mw-webapp/cypress/support/index.d.ts

Added Scenario_AnyUser_FillUserProfile test.
Added getFirstLetters command and refactored IsAuth_UserPersonalData_EditUserName test.
Changed scenario test IDs according documentation.

feat: #1449 add Scenario_AnyUser_FillUserProfile test

---

mw-webapp/cypress/accessIds/wayDescriptionAccessIds.ts
mw-webapp/cypress/e2e/scenarios/chat.cy.ts
mw-webapp/cypress/e2e/scenarios/mentorMentee.cy.ts
mw-webapp/cypress/e2e/userWays.cy.ts
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/fixtures/wayDescriptionFixture.json
mw-webapp/cypress/scopesSelectors/wayDescriptionSelectors.ts
mw-webapp/cypress/support/commands.ts
mw-webapp/cypress/support/index.d.ts
mw-webapp/src/logic/wayPage/MentorRequestsSection.tsx
mw-webapp/src/logic/wayPage/MentorsSection.tsx
mw-webapp/src/logic/wayPage/WayPage.tsx

Тест нестабильный (по той же причине, что и тесты на создание тэга и пути)

feat: #1455 add Scenario Mentor_AddAsWayMentor auto test

---

mw-webapp/cypress/accessIds/dayReportsAccessIds.ts
mw-webapp/cypress/e2e/compositeWays.cy.ts
mw-webapp/cypress/fixtures/testUserDataFixture.json
mw-webapp/cypress/scopesSelectors/dayReportsSelectors.ts
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableDateCell/ReportsTableDateCell.tsx
mw-webapp/src/logic/wayPage/reportsTable/reportsColumns/reportsTableJobsDoneCell/ReportsTableJobsDoneCell.tsx

Added checks for the presence of report dates, job done, time spent on job, and name of reporter.

feat: #1460 test refactoring  IsAuth_CompositeWay_Creation test

---

mw-webapp/cypress/accessIds/wayDescriptionAccessIds.ts
mw-webapp/cypress/e2e/compositeWays.cy.ts
mw-webapp/cypress/scopesSelectors/wayDescriptionSelectors.ts
mw-webapp/src/logic/wayPage/WayChildrenList/WayChildrenList.tsx

Added IsAuth_CompositeWay_DeleteWay test

feat: #1460 add IsAuth_CompositeWay_DeleteWay

---

mw-webapp/cypress/accessIds/userWaysAccessIds.ts
mw-webapp/cypress/e2e/userWays.cy.ts
mw-webapp/cypress/fixtures/userWaysFixture.json
mw-webapp/cypress/scopesSelectors/userWaysSelectors.ts
mw-webapp/src/logic/userPage/UserPage.tsx

Scope refactoring according test documentation.
Added  NoAuth_UserWay_ClickCollectionButton.

feat: #1339 add  NoAuth_UserWay_ClickCollectionButton

---

mw-webapp/src/logic/wayPage/WayChildrenList/WayChildrenList.tsx
mw-webapp/src/logic/wayPage/WayPage.tsx

Indicates whether the current user is the owner of way

feat: #1495 add isOwner to composite way

---

mw-webapp/src/App.tsx
mw-webapp/src/router/pages.tsx

- add independent route fron healthcheck

feat: #1486 create independentRoute

---

local.docker-compose.yml
mw-webapp/src/component/accordion/Accordion.cy.tsx
mw-webapp/src/component/accordion/Accordion.stories.tsx
mw-webapp/src/component/accordion/Accordion.tsx
mw-webapp/src/dictionary/WayPageContent.json
mw-webapp/src/land/mentorsLandingPage/MentorsLandingPage.tsx
mw-webapp/src/logic/aboutProjectPage/AboutProjectPage.tsx
mw-webapp/src/logic/wayPage/wayStatistics/statisticBlock/statisticItem/StatisticItem.tsx
mw-webapp/src/logic/wayPage/wayStatistics/statisticLabels/StatisticLabels.module.scss
mw-webapp/src/logic/wayPage/wayStatistics/statisticLabels/StatisticLabels.tsx

IMPORTANT!: changed filed local.docker-compose.yml line 49 driver: host => driver: bridge

fix: #1253 Add overflow to labels, fixed translate h in statistics

---

gateway/local.nginx.conf
mw-webapp/cypress/accessIds/wayDescriptionAccessIds.ts
mw-webapp/cypress/e2e/compositeWays.cy.ts
mw-webapp/cypress/scopesSelectors/wayDescriptionSelectors.ts
mw-webapp/src/component/dropdown/Dropdown.cy.tsx
mw-webapp/src/component/dropdown/Dropdown.module.scss
mw-webapp/src/component/dropdown/Dropdown.tsx
mw-webapp/src/component/dropdown/dropdownMenuItem/DropdownMenuItem.module.scss
mw-webapp/src/component/dropdown/dropdownMenuItem/DropdownMenuItem.tsx
mw-webapp/src/component/wayCollectionCard/WayCollectionCard.tsx
mw-webapp/src/dictionary/WayPageContent.json
mw-webapp/src/logic/chat/chatContent/ChatContent.tsx
mw-webapp/src/logic/wayPage/WayChildrenList/WayChildrenList.tsx
mw-webapp/src/logic/wayPage/WayPage.tsx
mw-webapp/src/logic/wayPage/WayPageStore.ts
mw-webapp/src/model/businessModel/Way.ts

Tests about composite ways doesn't works! Because when we delete participant - dayReports and statistics don't reload. I updated tests and logic

feat: #1273 Add possibility to use nested dropdown

---

local.docker-compose.yml
mw-webapp/src/logic/wayPage/WayChildrenList/WayChildrenList.tsx
mw-webapp/src/utils/DateUtils.ts

add sorted by update to compositeWay

geat: #1355 add sorted by update to compositeWay

---

mw-webapp/.storybook/preview.scss
mw-webapp/package.json
mw-webapp/pnpm-lock.yaml
mw-webapp/src/component/slider/Slider.scss
mw-webapp/src/component/slider/Slider.tsx
mw-webapp/src/component/slider/Sliders.stories.tsx
mw-webapp/src/land/mentorsLandingPage/MentorsLandingPage.module.scss
mw-webapp/src/land/mentorsLandingPage/MentorsLandingPage.tsx

https://github.com/user-attachments/assets/269f8e0e-7f79-46d7-b475-15e1e8debc09

feat: #1511 create slider
